name: k6 load test
on: [push]
permissions:
  contents: write
jobs:
  load-test:
    build: 
     name: k6 load test
     runs-on: ubuntu-latest
    steps:
      - name:  step 1 - checkout
          uses: actions/checkout@v3
       
      - name: step 2 - k6 load test
          uses: grafana/k6-action@v0.2.0
          with:
          filename: scripts/test.js 

      - run: ls & mkdir reports & mv index.html report
      
      - name : step 3 - upload artifact
          uses: actions/upload-artifact@v3
          with:
            name: relatório
            path: report
      
      - name : step 4 - publish report
          uses: peaceiris/actions-gh-pages@v3
          with: 
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_brackets: gh-pages
            publish_dir: reports

          
            
          